version: 2.0.0

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: db

volumes:
  mongo_data:
